### ISSUE TITLE
Show retaining objects

### ISSUE THREAD

**Issue by fgnass** [felixge/node-memory-leak-tutorial#1]
Hi Felix,

I thought this [patch for the v8-profiler](http://fgnass.posterous.com/finding-memory-leaks-in-nodejs-applications) might be interesting in this context, as it allows you to show the retaining objects.

**Comment by fgnass** [comment]
I'm closing this as this isn't an issue at all and non-issues suck ;) Project-related messages would be an awesome GitHub feature.

**Comment by felixge** [comment]
A pull request adding the link to the Readme would seem nice here : )
